export const ArticlesData = [
  {
    img_path: "/src/assets/imgs/articles/city.jpeg",
    title: "Um verdadeiro mar de oportuinidades com o 5g (1)",
    leading:
      "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
    content_path: "/src/components/articles/markdowns/ia.md",
    published_date: "03/29/2023",
    updated_date: "03/29/2023",
    tags: ["5g", "IoT", "AI"],
    author: "Wendell Oliveira",
    img_credits: "this text represents imgs credits",
  },
  {
    img_path: "/src/assets/imgs/articles/drone.jpeg",
    title: "Entenda o que é blockchain de uma vez por todas (2)",
    leading:
      "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
    content_path: "/src/components/articles/markdowns/5g.md",
    published_date: "03/29/2023",
    updated_date: "03/29/2023",
    tags: ["Cloud", "Blockchain", "Cybersecurity"],
    author: "Wendell Oliveira",
    img_credits: "this text represents imgs credits",
  },
  {
    img_path: "/src/assets/imgs/articles/setup.webp",
    title: "Web 3.0 desafios e oportunidades (3)",
    leading:
      "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
    content_path: "/src/components/articles/markdowns/LLM.md",
    published_date: "03/29/2023",
    updated_date: "03/29/2023",
    tags: ["5g", "Cloud", "Cybersecurity"],
    author: "Wendell Oliveira",
    img_credits: "this text represents imgs credits",
  },
  {
    img_path: "/src/assets/imgs/articles/work.webp",
    title: "O futuro das cryptos nunca mais será o mesmo (4)",
    leading:
      "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
    content_path: "/src/components/articles/markdowns/cybersecurity.md",
    published_date: "03/29/2023",
    updated_date: "03/29/2023",
    tags: ["AI", "Cybersecurity", "Data"],
    author: "Wendell Oliveira",
    img_credits: "this text represents imgs credits",
  },
  {
    img_path: "/src/assets/imgs/articles/city.jpeg",
    title: "Um verdadeiro mar de oportuinidades com o 5g (5)",
    leading:
      "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
    content_path: "/src/components/articles/markdowns/ia.md",
    published_date: "03/29/2023",
    updated_date: "03/29/2023",
    tags: ["5g", "IoT", "AI"],
    author: "Wendell Oliveira",
    img_credits: "this text represents imgs credits",
  },
  {
    img_path: "/src/assets/imgs/articles/drone.jpeg",
    title: "Entenda o que é blockchain de uma vez por todas (6)",
    leading:
      "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
    content_path: "/src/components/articles/markdowns/5g.md",
    published_date: "03/29/2023",
    updated_date: "03/29/2023",
    tags: ["Cloud", "Blockchain", "Cybersecurity"],
    author: "Wendell Oliveira",
    img_credits: "this text represents imgs credits",
  },
  {
    img_path: "/src/assets/imgs/articles/setup.webp",
    title: "Web 3.0 desafios e oportunidades (7)",
    leading:
      "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
    content_path: "/src/components/articles/markdowns/LLM.md",
    published_date: "03/29/2023",
    updated_date: "03/29/2023",
    tags: ["5g", "Cloud", "Cybersecurity"],
    author: "Wendell Oliveira",
    img_credits: "this text represents imgs credits",
  },
  {
    img_path: "/src/assets/imgs/articles/work.webp",
    title: "O futuro das cryptos nunca mais será o mesmo (8)",
    leading:
      "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
    content_path: "/src/components/articles/markdowns/cybersecurity.md",
    published_date: "03/29/2023",
    updated_date: "03/29/2023",
    tags: ["AI", "Cybersecurity", "Data"],
    author: "Wendell Oliveira",
    img_credits: "this text represents imgs credits",
  },
  {
    img_path: "/src/assets/imgs/articles/city.jpeg",
    title: "Um verdadeiro mar de oportuinidades com o 5g (9)",
    leading:
      "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
    content_path: "/src/components/articles/markdowns/ia.md",
    published_date: "03/29/2023",
    updated_date: "03/29/2023",
    tags: ["5g", "IoT", "AI"],
    author: "Wendell Oliveira",
    img_credits: "this text represents imgs credits",
  },
  {
    img_path: "/src/assets/imgs/articles/drone.jpeg",
    title: "Entenda o que é blockchain de uma vez por todas (10)",
    leading:
      "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
    content_path: "/src/components/articles/markdowns/5g.md",
    published_date: "03/29/2023",
    updated_date: "03/29/2023",
    tags: ["Cloud", "Blockchain", "Cybersecurity"],
    author: "Wendell Oliveira",
    img_credits: "this text represents imgs credits",
  },
  {
    img_path: "/src/assets/imgs/articles/setup.webp",
    title: "Web 3.0 desafios e oportunidades (11)",
    leading:
      "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
    content_path: "/src/components/articles/markdowns/LLM.md",
    published_date: "03/29/2023",
    updated_date: "03/29/2023",
    tags: ["5g", "Cloud", "Cybersecurity"],
    author: "Wendell Oliveira",
    img_credits: "this text represents imgs credits",
  },
  {
    img_path: "/src/assets/imgs/articles/work.webp",
    title: "O futuro das cryptos nunca mais será o mesmo (12)",
    leading:
      "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",
    content_path: "/src/components/articles/markdowns/cybersecurity.md",
    published_date: "03/29/2023",
    updated_date: "03/29/2023",
    tags: ["AI", "Cybersecurity", "Data"],
    author: "Wendell Oliveira",
    img_credits: "this text represents imgs credits",
  },
];
