import { ProjectsData } from "../ProjectsData";
import Timers from "../timers/Timers";
import Tasks from "../tasks/Tasks";
import Agenda from "../agenda/Agenda";
import Notes from "../notes/Notes";
import Books from "../books/Books";
import Goals from "../goals/Goals";
import Wishlist from "../wishlist/Wishlist";
import YoutubeDown from "../youtubedown/YoutubeDown";

export const ElementsRoutes: Map<string, JSX.Element> = new Map<
  string,
  JSX.Element
>();

ElementsRoutes.set(ProjectsData[0].title, <Timers />);
ElementsRoutes.set(ProjectsData[1].title, <Tasks />);
ElementsRoutes.set(ProjectsData[2].title, <Agenda />);
ElementsRoutes.set(ProjectsData[3].title, <Notes />);
ElementsRoutes.set(ProjectsData[4].title, <Books />);
ElementsRoutes.set(ProjectsData[5].title, <Goals />);
ElementsRoutes.set(ProjectsData[6].title, <Wishlist />);
ElementsRoutes.set(ProjectsData[7].title, <YoutubeDown />);
ElementsRoutes.set(ProjectsData[8].title, <Timers />);
ElementsRoutes.set(ProjectsData[9].title, <Tasks />);
ElementsRoutes.set(ProjectsData[10].title, <Agenda />);
ElementsRoutes.set(ProjectsData[11].title, <Notes />);
ElementsRoutes.set(ProjectsData[12].title, <Books />);
ElementsRoutes.set(ProjectsData[13].title, <Goals />);
ElementsRoutes.set(ProjectsData[14].title, <Wishlist />);
ElementsRoutes.set(ProjectsData[15].title, <YoutubeDown />);
ElementsRoutes.set(ProjectsData[16].title, <Timers />);
ElementsRoutes.set(ProjectsData[17].title, <Tasks />);
ElementsRoutes.set(ProjectsData[18].title, <Agenda />);
ElementsRoutes.set(ProjectsData[19].title, <Notes />);
ElementsRoutes.set(ProjectsData[20].title, <Books />);
ElementsRoutes.set(ProjectsData[21].title, <Goals />);
ElementsRoutes.set(ProjectsData[22].title, <Wishlist />);
ElementsRoutes.set(ProjectsData[23].title, <YoutubeDown />);
ElementsRoutes.set(ProjectsData[24].title, <Timers />);
ElementsRoutes.set(ProjectsData[25].title, <Tasks />);
ElementsRoutes.set(ProjectsData[26].title, <Agenda />);
ElementsRoutes.set(ProjectsData[27].title, <Notes />);
ElementsRoutes.set(ProjectsData[28].title, <Books />);
ElementsRoutes.set(ProjectsData[29].title, <Goals />);
ElementsRoutes.set(ProjectsData[30].title, <Wishlist />);
ElementsRoutes.set(ProjectsData[31].title, <YoutubeDown />);
ElementsRoutes.set(ProjectsData[32].title, <Timers />);
ElementsRoutes.set(ProjectsData[33].title, <Tasks />);
ElementsRoutes.set(ProjectsData[34].title, <Agenda />);
ElementsRoutes.set(ProjectsData[35].title, <Notes />);
ElementsRoutes.set(ProjectsData[36].title, <Books />);
ElementsRoutes.set(ProjectsData[37].title, <Goals />);
ElementsRoutes.set(ProjectsData[38].title, <Wishlist />);
ElementsRoutes.set(ProjectsData[39].title, <YoutubeDown />);
ElementsRoutes.set(ProjectsData[40].title, <Timers />);
ElementsRoutes.set(ProjectsData[41].title, <Tasks />);
ElementsRoutes.set(ProjectsData[42].title, <Agenda />);
ElementsRoutes.set(ProjectsData[43].title, <Notes />);
ElementsRoutes.set(ProjectsData[44].title, <Books />);
ElementsRoutes.set(ProjectsData[45].title, <Goals />);
ElementsRoutes.set(ProjectsData[46].title, <Wishlist />);
ElementsRoutes.set(ProjectsData[47].title, <YoutubeDown />);
ElementsRoutes.set(ProjectsData[48].title, <Timers />);
ElementsRoutes.set(ProjectsData[49].title, <Tasks />);
ElementsRoutes.set(ProjectsData[50].title, <Agenda />);
ElementsRoutes.set(ProjectsData[51].title, <Notes />);
ElementsRoutes.set(ProjectsData[52].title, <Books />);
ElementsRoutes.set(ProjectsData[53].title, <Goals />);
ElementsRoutes.set(ProjectsData[54].title, <Wishlist />);
ElementsRoutes.set(ProjectsData[55].title, <YoutubeDown />);
ElementsRoutes.set(ProjectsData[56].title, <Timers />);
ElementsRoutes.set(ProjectsData[57].title, <Tasks />);
ElementsRoutes.set(ProjectsData[58].title, <Agenda />);
ElementsRoutes.set(ProjectsData[59].title, <Notes />);
ElementsRoutes.set(ProjectsData[60].title, <Books />);
ElementsRoutes.set(ProjectsData[61].title, <Goals />);
ElementsRoutes.set(ProjectsData[62].title, <Wishlist />);
ElementsRoutes.set(ProjectsData[63].title, <YoutubeDown />);
ElementsRoutes.set(ProjectsData[64].title, <Timers />);
ElementsRoutes.set(ProjectsData[65].title, <Tasks />);
ElementsRoutes.set(ProjectsData[66].title, <Agenda />);
ElementsRoutes.set(ProjectsData[67].title, <Notes />);
ElementsRoutes.set(ProjectsData[68].title, <Books />);
ElementsRoutes.set(ProjectsData[69].title, <Goals />);
ElementsRoutes.set(ProjectsData[70].title, <Wishlist />);
ElementsRoutes.set(ProjectsData[71].title, <YoutubeDown />);
ElementsRoutes.set(ProjectsData[71].title, <Timers />);
ElementsRoutes.set(ProjectsData[73].title, <Tasks />);
ElementsRoutes.set(ProjectsData[74].title, <Agenda />);
ElementsRoutes.set(ProjectsData[75].title, <Notes />);
ElementsRoutes.set(ProjectsData[76].title, <Books />);
ElementsRoutes.set(ProjectsData[77].title, <Goals />);
ElementsRoutes.set(ProjectsData[78].title, <Wishlist />);
ElementsRoutes.set(ProjectsData[79].title, <YoutubeDown />);
