export const MockedTickerData = [
  {
    id: 1,
    stock: "MELI",
    price: 125.8,
    img_path: "/src/assets/imgs/ticker-logos/meli.svg",
    change: 0.12,
    changePercent: 0.12,
    marketStatus: "closed",
  },
  {
    id: 2,
    stock: "AAPL",
    price: 164.46,
    img_path: "/src/assets/imgs/ticker-logos/apple.svg",
    change: 0.12,
    changePercent: 0.12,
    marketStatus: "open",
  },
  {
    id: 3,
    stock: "IBM",
    price: 125.81,
    img_path: "/src/assets/imgs/ticker-logos/ibm.svg",
    change: 0.12,
    changePercent: 0.12,
    marketStatus: "open",
  },
  {
    id: 4,
    stock: "AMD",
    price: 84.4,
    img_path: "/src/assets/imgs/ticker-logos/amd.svg",
    change: 0.12,
    changePercent: 0.12,
    marketStatus: "open",
  },
  {
    id: 5,
    stock: "GOOG",
    price: 105.49,
    img_path: "/src/assets/imgs/ticker-logos/google.svg",
    change: 0.12,
    changePercent: 0.12,
    marketStatus: "open",
  },
  {
    id: 6,
    stock: "MSFT",
    price: 276.48,
    img_path: "/src/assets/imgs/ticker-logos/microsoft.svg",
    change: 0.12,
    changePercent: 0.12,
    marketStatus: "open",
  },
  {
    id: 7,
    stock: "NVDA",
    price: 264.47,
    img_path: "/src/assets/imgs/ticker-logos/nvidia.svg",
    change: 0.12,
    changePercent: 0.12,
    marketStatus: "open",
  },
  {
    id: 8,
    stock: "NFLX",
    price: 321.89,
    img_path: "/src/assets/imgs/ticker-logos/netflix.svg",
    change: 0.12,
    changePercent: 0.12,
    marketStatus: "closed",
  },
  {
    id: 9,
    stock: "TSM",
    price: 82.48,
    img_path: "/src/assets/imgs/ticker-logos/apple.svg",
    change: 0.12,
    changePercent: 0.12,
    marketStatus: "closed",
  },
  {
    id: 10,
    stock: "QCOM",
    price: 114.5,
    img_path: "/src/assets/imgs/ticker-logos/qualcomm.svg",
    change: 0.12,
    changePercent: 0.12,
    marketStatus: "closed",
  },
  {
    id: 11,
    stock: "INTC",
    price: 29.1,
    img_path: "/src/assets/imgs/ticker-logos/intel.svg",
    change: 0.12,
    changePercent: 0.12,
    marketStatus: "closed",
  },
  {
    id: 12,
    stock: "BITCOIN",
    symbol: "BTC-USD",
    price: 27657,
    img_path: "/src/assets/imgs/ticker-logos/bitcoin.svg",
    change: 0.12,
    changePercent: 0.12,
    marketStatus: "open",
  },
  {
    id: 13,
    stock: "ETHEREUM",
    symbol: "ETH-USD",
    price: 1837,
    img_path: "/src/assets/imgs/ticker-logos/eth.svg",
    change: 0.12,
    changePercent: 0.12,
    marketStatus: "open",
  },
  {
    id: 14,
    stock: "GOLD",
    price: 2008.45,
    img_path: "/src/assets/imgs/ticker-logos/apple.svg",
    change: 0.12,
    changePercent: 0.12,
    marketStatus: "closed",
  },
  {
    id: 15,
    stock: "USDBRL",
    price: 5.07,
    img_path: "/src/assets/imgs/ticker-logos/apple.svg",
    change: 0.12,
    changePercent: 0.12,
    marketStatus: "closed",
  },
  {
    id: 16,
    stock: "USDJPY",
    price: 133.52,
    img_path: "/src/assets/imgs/ticker-logos/apple.svg",
    change: 0.12,
    changePercent: 0.12,
    marketStatus: "closed",
  },
  {
    id: 17,
    stock: "USDEUR",
    price: 0.91,
    img_path: "/src/assets/imgs/ticker-logos/apple.svg",
    change: 0.12,
    changePercent: 0.12,
    marketStatus: "closed",
  },
];
