import { Task } from './hooks/types';

export const TasksMockedData: Task[] = [
  {
    id: '1',
    title: 'Task 1',
    description: 'Task 1 description',
    status: 'To Do',
    priority: 'red',
    difficulty: 'very_low',
    estimated_time: 60,
    due_date: '2021-01-01',
    due_time: '12:00',
  },
  {
    id: '2',
    title: 'Task 2',
    description: 'Task 2 description',
    status: 'To Do',
    priority: 'red',
    difficulty: 'medium',
    estimated_time: 60,
    due_date: '2021-01-01',
    due_time: '12:00',
  },
  {
    id: '3',
    title: 'Task 3',
    description: 'Task 3 description',
    status: 'To Do',
    priority: 'red',
    difficulty: 'very_high',
    estimated_time: 60,
    due_date: '2021-01-01',
    due_time: '12:00',
  },
  {
    id: '4',
    title: 'Task 4',
    description: 'Task 4 description',
    status: 'To Do',
    priority: 'red',
    difficulty: 'high',
    estimated_time: 60,
    due_date: '2021-01-01',
    due_time: '12:00',
  },
  {
    id: '5',
    title: 'Task 5',
    description: 'Task 5 description',
    status: 'To Do',
    priority: 'red',
    difficulty: 'very_high',
    estimated_time: 60,
    due_date: '2021-01-01',
    due_time: '12:00',
  },
  {
    id: '6',
    title: 'Task 6',
    description: 'Task 6 description',
    status: 'In Progress',
    priority: 'red',
    difficulty: 'medium',
    estimated_time: 60,
    due_date: '2021-01-01',
    due_time: '12:00',
  },
  {
    id: '7',
    title: 'Task 7',
    description: 'Task 7 description',
    status: 'Done',
    priority: 'red',
    difficulty: 'low',
    estimated_time: 60,
    due_date: '2021-01-01',
    due_time: '12:00',
  },
  {
    id: '8',
    title: 'Task 8',
    description: 'Task 8 description',
    status: 'To Do',
    priority: 'orange',
    difficulty: 'very_high',
    estimated_time: 60,
    due_date: '2021-01-01',
    due_time: '12:00',
  },
  {
    id: '9',
    title: 'Task 9',
    description: 'Task 9 description',
    status: 'In Progress',
    priority: 'orange',
    difficulty: 'very_high',
    estimated_time: 60,
    due_date: '2021-01-01',
    due_time: '12:00',
  },
  {
    id: '10',
    title: 'Task 10',
    description: 'Task 10 description',
    status: 'In Progress',
    priority: 'orange',
    difficulty: 'high',
    estimated_time: 60,
    due_date: '2021-01-01',
    due_time: '12:00',
  },
  {
    id: '11',
    title: 'Task 11',
    description: 'Task 11 description',
    status: 'In Progress',
    priority: 'orange',
    difficulty: 'medium',
    estimated_time: 60,
    due_date: '2021-01-01',
    due_time: '12:00',
  },
  {
    id: '12',
    title: 'Task 12',
    description: 'Task 12 description',
    status: 'In Progress',
    priority: 'orange',
    difficulty: 'high',
    estimated_time: 60,
    due_date: '2021-01-01',
    due_time: '12:00',
  },
  {
    id: '13',
    title: 'Task 13',
    description: 'Task 13 description',
    status: 'In Progress',
    priority: 'orange',
    difficulty: 'very_high',
    estimated_time: 60,
    due_date: '2021-01-01',
    due_time: '12:00',
  },
  {
    id: '14',
    title: 'Task 14',
    description: 'Task 14 description',
    status: 'Done',
    priority: 'orange',
    difficulty: 'medium',
    estimated_time: 60,
    due_date: '2021-01-01',
    due_time: '12:00',
  },
  {
    id: '15',
    title: 'Task 15',
    description: 'Task 15 description',
    status: 'To Do',
    priority: 'yellow',
    difficulty: 'low',
    estimated_time: 60,
    due_date: '2021-01-01',
    due_time: '12:00',
  },
  {
    id: '16',
    title: 'Task 16',
    description: 'Task 16 description',
    status: 'To Do',
    priority: 'yellow',
    difficulty: 'very_low',
    estimated_time: 60,
    due_date: '2021-01-01',
    due_time: '12:00',
  },
  {
    id: '17',
    title: 'Task 17',
    description: 'Task 17 description',
    status: 'In Progress',
    priority: 'yellow',
    difficulty: 'very_low',
    estimated_time: 60,
    due_date: '2021-01-01',
    due_time: '12:00',
  },
  {
    id: '18',
    title: 'Task 18',
    description: 'Task 18 description',
    status: 'Done',
    priority: 'yellow',
    difficulty: 'medium',
    estimated_time: 60,
    due_date: '2021-01-01',
    due_time: '12:00',
  },
  {
    id: '19',
    title: 'Task 19',
    description: 'Task 19 description',
    status: 'Done',
    priority: 'yellow',
    difficulty: 'very_low',
    estimated_time: 60,
    due_date: '2021-01-01',
    due_time: '12:00',
  },
  {
    id: '20',
    title: 'Task 20',
    description: 'Task 20 description',
    status: 'Done',
    priority: 'yellow',
    difficulty: 'low',
    estimated_time: 60,
    due_date: '2021-01-01',
    due_time: '12:00',
  },
  {
    id: '21',
    title: 'Task 21',
    description: 'Task 21 description',
    status: 'Done',
    priority: 'yellow',
    difficulty: 'medium',
    estimated_time: 60,
    due_date: '2021-01-01',
    due_time: '12:00',
  },
  {
    id: '22',
    title: 'Task 22',
    description: 'Task 22 description',
    status: 'To Do',
    priority: 'green',
    difficulty: 'medium',
    estimated_time: 60,
    due_date: '2021-01-01',
    due_time: '12:00',
  },
  {
    id: '23',
    title: 'Task 23',
    description: 'Task 23 description',
    status: 'To Do',
    priority: 'green',
    difficulty: 'very_low',
    estimated_time: 60,
    due_date: '2021-01-01',
    due_time: '12:00',
  },
  {
    id: '24',
    title: 'Task 24',
    description: 'Task 24 description',
    status: 'In Progress',
    priority: 'green',
    difficulty: 'low',
    estimated_time: 60,
    due_date: '2021-01-01',
    due_time: '12:00',
  },
  {
    id: '25',
    title: 'Task 25',
    description: 'Task 25 description',
    status: 'In Progress',
    priority: 'green',
    difficulty: 'high',
    estimated_time: 60,
    due_date: '2021-01-01',
    due_time: '12:00',
  },
  {
    id: '26',
    title: 'Task 26',
    description: 'Task 26 description',
    status: 'In Progress',
    priority: 'green',
    difficulty: 'very_high',
    estimated_time: 60,
    due_date: '2021-01-01',
    due_time: '12:00',
  },
  {
    id: '27',
    title: 'Task 27',
    description: 'Task 27 description',
    status: 'Done',
    priority: 'green',
    difficulty: 'medium',
    estimated_time: 60,
    due_date: '2021-01-01',
    due_time: '12:00',
  },
  {
    id: '28',
    title: 'Task 28',
    description: 'Task 28 description',
    status: 'Done',
    priority: 'green',
    difficulty: 'low',
    estimated_time: 60,
    due_date: '2021-01-01',
    due_time: '12:00',
  },
];
